name: ViaVersion
main: com.viaversion.viaversion.ViaVersionPlugin
authors: [ _MylesC, creeper123123321, Gerrygames, kennytv, Matsv, EnZaXD, RK_01 ]
version: ${version}
description: ${description}
website: ${url}
api-version: 1.13
folia-supported: true
loadbefore: [ ProtocolLib ]
commands:
  viaversion:
    permission: viaversion.command # The permission is also referenced here to filter root suggestions (/via<tab>)
    description: Shows ViaVersion Version and more.
    aliases: [ viaver, vvbukkit ]
permissions:
  viaversion.admin:
    default: op
    children:
      viaversion.command.autoteam: true
      viaversion.command.debug: true
      viaversion.command.displayleaks: true
      viaversion.command.dontbugme: true
      viaversion.command.dump: true
      viaversion.command.list: true
      viaversion.command.pps: true
      viaversion.command.reload: true
