package us.myles.ViaVersion.protocols.protocolsnapshotto1_12_2.data;


import com.google.common.base.Optional;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

// Constant type changes to stop depending on names (the EntityTypes1_13 will be auto-generated so some fields can be obfuscated)
public class EntityTypeRewriter {
    private static Map<Integer, Integer> entityTypes = new ConcurrentHashMap<>();

    static {
        // Generated by codename Bevet

        // Entities 1.12 -> 18w15a
        regEnt(1, 32); // item - ajl
        regEnt(2, 22); // xp_orb - abx
        regEnt(3, 0); // area_effect_cloud - abp
        regEnt(4, 15); // elder_guardian - aju
        regEnt(5, 84); // wither_skeleton - aku
        regEnt(6, 71); // stray - akq
        regEnt(7, 74); // egg - alz
        regEnt(8, 35); // leash_knot - ajb
        regEnt(9, 49); // painting - ajd
        regEnt(10, 2); // arrow - all
        regEnt(11, 67); // snowball - alw
        regEnt(12, 34); // fireball - alq
        regEnt(13, 65); // small_fireball - alv
        regEnt(14, 75); // ender_pearl - ama
        regEnt(15, 23); // eye_of_ender_signal - alo
        regEnt(16, 77); // potion - amc
        regEnt(17, 76); // xp_bottle - amb
        regEnt(18, 33); // item_frame - aja
        regEnt(19, 85); // wither_skull - ame
        regEnt(20, 55); // tnt - ajm
        regEnt(21, 24); // falling_block - ajk
        regEnt(22, 25); // fireworks_rocket - alp
        regEnt(23, 30); // husk - akc
        regEnt(24, 68); // spectral_arrow - alx
        regEnt(25, 60); // shulker_bullet - alu
        regEnt(26, 13); // dragon_fireball - alm
        regEnt(27, 89); // zombie_villager - akw
        regEnt(28, 63); // skeleton_horse - aht
        regEnt(29, 88); // zombie_horse - ahv
        regEnt(30, 1); // armor_stand - aiy
        regEnt(31, 11); // donkey - aho
        regEnt(32, 46); // mule - ahs
        regEnt(33, 20); // evocation_fangs - aln
        regEnt(34, 21); // evocation_illager - ajy
        regEnt(35, 78); // vex - akr
        regEnt(36, 81); // vindication_illager - aks
        regEnt(37, 31); // illusion_illager - akd
        regEnt(40, 41); // commandblock_minecart - aml
        regEnt(41, 5); // boat - ami
        regEnt(42, 39); // minecart - amj
        regEnt(43, 40); // chest_minecart - amk
        regEnt(44, 42); // furnace_minecart - amm
        regEnt(45, 45); // tnt_minecart - amp
        regEnt(46, 43); // hopper_minecart - amn
        regEnt(47, 44); // spawner_minecart - amo
        regEnt(50, 10); // creeper - ajs
        regEnt(51, 62); // skeleton - akm
        regEnt(52, 69); // spider - akp
        regEnt(53, 27); // giant - aka
        regEnt(54, 87); // zombie - akv
        regEnt(55, 64); // slime - akn
        regEnt(56, 26); // ghast - ajz
        regEnt(57, 53); // zombie_pigman - akh
        regEnt(58, 18); // enderman - ajv
        regEnt(59, 6); // cave_spider - ajr
        regEnt(60, 61); // silverfish - akl
        regEnt(61, 4); // blaze - ajq
        regEnt(62, 38); // magma_cube - ake
        regEnt(63, 17); // ender_dragon - aic
        regEnt(64, 83); // wither - aiw
        regEnt(65, 3); // bat - agl
        regEnt(66, 82); // witch - akt
        regEnt(67, 19); // endermite - ajw
        regEnt(68, 28); // guardian - akb
        regEnt(69, 59); // shulker - akk
        regEnt(200, 16); // ender_crystal - aib
        regEnt(90, 51); // pig - agy
        regEnt(91, 58); // sheep - ahd
        regEnt(92, 9); // cow - ags
        regEnt(93, 7); // chicken - agq
        regEnt(94, 70); // squid - ahg
        regEnt(95, 86); // wolf - ahl
        regEnt(96, 47); // mooshroom - agv
        regEnt(97, 66); // snowman - ahf
        regEnt(98, 48); // ocelot - agw
        regEnt(99, 80); // villager_golem - ahj
        regEnt(100, 29); // horse - ahp
        regEnt(101, 56); // rabbit - ahb
        regEnt(102, 54); // polar_bear - agz
        regEnt(103, 36); // llama - ahr
        regEnt(104, 37); // llama_spit - alr
        regEnt(105, 50); // parrot - agx
        regEnt(120, 79); // villager - ala


        // OBJECTS
        // Couldn't find any object id change with mapped values

    }

    private static void regEnt(int type1_12, int type1_13) {
        entityTypes.put(type1_12, type1_13);
    }

    public static Optional<Integer> getNewId(int type1_12) {
        return Optional.fromNullable(entityTypes.get(type1_12));
    }
}
