package us.myles.ViaVersion.protocols.protocolsnapshotto1_12_2.data;


import com.google.common.base.Optional;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

// Constant type changes to stop depending on names (the EntityTypes1_13 will be auto-generated so some fields can be obfuscated)
public class EntityTypeRewriter {
    private static Map<Integer, Integer> entityTypes = new ConcurrentHashMap<>();

    static {
        // Generated by Bevet

        // Entities 1.12 -> 18w11a
        regEnt(1, 31); // item
        regEnt(2, 21); // xp_orb
        regEnt(3, 0); // area_effect_cloud
        regEnt(4, 14); // elder_guardian
        regEnt(5, 83); // wither_skeleton
        regEnt(6, 70); // stray
        regEnt(7, 73); // egg
        regEnt(8, 34); // leash_knot
        regEnt(9, 48); // painting
        regEnt(10, 2); // arrow
        regEnt(11, 66); // snowball
        regEnt(12, 33); // fireball
        regEnt(13, 64); // small_fireball
        regEnt(14, 74); // ender_pearl
        regEnt(15, 22); // eye_of_ender_signal
        regEnt(16, 76); // potion
        regEnt(17, 75); // xp_bottle
        regEnt(18, 32); // item_frame
        regEnt(19, 84); // wither_skull
        regEnt(20, 54); // tnt
        regEnt(21, 23); // falling_block
        regEnt(22, 24); // fireworks_rocket
        regEnt(23, 29); // husk
        regEnt(24, 67); // spectral_arrow
        regEnt(25, 59); // shulker_bullet
        regEnt(26, 12); // dragon_fireball
        regEnt(27, 88); // zombie_villager
        regEnt(28, 62); // skeleton_horse
        regEnt(29, 87); // zombie_horse
        regEnt(30, 1); // armor_stand
        regEnt(31, 11); // donkey
        regEnt(32, 45); // mule
        regEnt(33, 19); // evocation_fangs
        regEnt(34, 20); // evocation_illager
        regEnt(35, 77); // vex
        regEnt(36, 80); // vindication_illager
        regEnt(37, 30); // illusion_illager
        regEnt(40, 40); // commandblock_minecart
        regEnt(41, 5); // boat
        regEnt(42, 38); // minecart
        regEnt(43, 39); // chest_minecart
        regEnt(44, 41); // furnace_minecart
        regEnt(45, 44); // tnt_minecart
        regEnt(46, 42); // hopper_minecart
        regEnt(47, 43); // spawner_minecart
        regEnt(50, 10); // creeper
        regEnt(51, 61); // skeleton
        regEnt(52, 68); // spider
        regEnt(53, 26); // giant
        regEnt(54, 86); // zombie
        regEnt(55, 63); // slime
        regEnt(56, 25); // ghast
        regEnt(57, 52); // zombie_pigman
        regEnt(58, 17); // enderman
        regEnt(59, 6); // cave_spider
        regEnt(60, 60); // silverfish
        regEnt(61, 4); // blaze
        regEnt(62, 37); // magma_cube
        regEnt(63, 16); // ender_dragon
        regEnt(64, 82); // wither
        regEnt(65, 3); // bat
        regEnt(66, 81); // witch
        regEnt(67, 18); // endermite
        regEnt(68, 27); // guardian
        regEnt(69, 58); // shulker
        regEnt(200, 15); // ender_crystal
        regEnt(90, 50); // pig
        regEnt(91, 57); // sheep
        regEnt(92, 9); // cow
        regEnt(93, 7); // chicken
        regEnt(94, 69); // squid
        regEnt(95, 85); // wolf
        regEnt(96, 46); // mooshroom
        regEnt(97, 65); // snowman
        regEnt(98, 47); // ocelot
        regEnt(99, 79); // villager_golem
        regEnt(100, 28); // horse
        regEnt(101, 55); // rabbit
        regEnt(102, 53); // polar_bear
        regEnt(103, 35); // llama
        regEnt(104, 36); // llama_spit
        regEnt(105, 49); // parrot
        regEnt(120, 78); // villager


        // OBJECTS
        // Couldn't find any object id changes
    }

    private static void regEnt(int type1_12, int type1_13) {
        entityTypes.put(type1_12, type1_13);
    }

    public static Optional<Integer> getNewId(int type1_12) {
        return Optional.fromNullable(entityTypes.get(type1_12));
    }
}
